version: '3.8'

services:
  project:
    build: ./project
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - rabbitmq
      - postgres
    env_file:
      - ./project/.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - ENVIRONMENT=prod
    container_name: https-api-project

  user-project:
    build: ./user-project
    ports:
      - "3000:3000"
    env_file:
      - ./user-project/.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - ENVIRONMENT=prod
    depends_on:
      - redis
      - rabbitmq
      - postgres
    container_name: https-api-user-project

  auth-project:
    build: ./auth-project
    env_file:
      - ./auth-project/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ENVIRONMENT=prod
    depends_on:
      - redis
      - rabbitmq
      - postgres
    container_name: https-api-auth-project

  utility-project:
    build: ./utility-project
    env_file:
      - ./utility-project/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ENVIRONMENT=prod
    depends_on:
      - redis
      - rabbitmq
      - postgres
    container_name: https-api-utility-project

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5430:5432

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15670:15672"
      - "5670:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src/secrets:/etc/nginx/ssl
      - ./uploads:/var/www/uploads
    depends_on:
      - project
      - user-project
      - auth-project
      - utility-project

volumes:
  redis-data:
  rabbitmq-data: