version: '3.8'

services:
  project:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    container_name: myapp

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15670:15672"
      - "5670:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../default.conf:/etc/nginx/conf.d/default.conf
      - ./src/secrets:/etc/nginx/ssl
      - ../uploads:/var/www/uploads

    depends_on:
      - project

volumes:
  redis-data:
  rabbitmq-data: